#!/usr/bin/env bash
# Deploy a staged worker payload and the windows selected by potluck-server.
#
# This is an internal controller hook. The server supplies an ordered route
# file and the owner index; users do not choose ranks, bounds, ports, or shards.
#
# Usage: scripts/deploy.sh --model MODEL.gguf --target SSH_TARGET \
#            --owner INDEX --route-file ROUTE_FILE [--ssh-port PORT]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO="$(cd "${SCRIPT_DIR}/.." && pwd -P)"

fail() {
    printf 'potluck-deploy: %s\n' "$*" >&2
    exit 1
}

usage() {
    cat <<'EOF'
usage: deploy.sh --model MODEL.gguf --target SSH_TARGET \
    --owner INDEX --route-file ROUTE_FILE [--ssh-port PORT]

The route file is generated by potluck-server. Each non-comment line is:
  WINDOW_INDEX OWNER_INDEX START_LAYER END_LAYER
EOF
    exit 2
}

shell_quote() {
    local value="$1"
    value="${value//\'/\'\\\'\'}"
    printf "'%s'" "${value}"
}

sha256_file() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | cut -d' ' -f1
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | cut -d' ' -f1
    else
        fail 'need sha256sum or shasum to verify files'
    fi
}

valid_target() {
    [[ "$1" != -* && "$1" =~ ^([A-Za-z0-9._-]+@)?[A-Za-z0-9._-]+$ ]]
}

model=""
target=""
owner=""
route_file=""
ssh_port=""
shard_bin="${POTLUCK_SHARD_BIN:-}"
dist_dir="${POTLUCK_DIST_DIR:-${REPO}/dist}"
cache_root="${POTLUCK_SHARD_CACHE:-${REPO}/.potluck-shards}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --model)
            [[ $# -ge 2 && -n "$2" ]] || usage
            model="$2"
            shift 2
            ;;
        --target)
            [[ $# -ge 2 && -n "$2" ]] || usage
            target="$2"
            shift 2
            ;;
        --owner)
            [[ $# -ge 2 && -n "$2" ]] || usage
            owner="$2"
            shift 2
            ;;
        --route-file)
            [[ $# -ge 2 && -n "$2" ]] || usage
            route_file="$2"
            shift 2
            ;;
        --ssh-port)
            [[ $# -ge 2 && -n "$2" ]] || usage
            ssh_port="$2"
            shift 2
            ;;
        --shard-bin)
            [[ $# -ge 2 && -n "$2" ]] || usage
            shard_bin="$2"
            shift 2
            ;;
        --dist-dir)
            [[ $# -ge 2 && -n "$2" ]] || usage
            dist_dir="$2"
            shift 2
            ;;
        --cache-dir)
            [[ $# -ge 2 && -n "$2" ]] || usage
            cache_root="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            usage
            ;;
    esac
done

[[ -f "${model}" ]] || fail "model does not exist: ${model}"
[[ -f "${route_file}" ]] || fail "route file does not exist: ${route_file}"
[[ -n "${target}" ]] || fail '--target is required'
valid_target "${target}" || fail "invalid SSH target: ${target}"
[[ "${owner}" =~ ^[0-9]+$ ]] || fail "invalid owner index: ${owner}"
command -v ssh >/dev/null 2>&1 || fail 'required command not found: ssh'
command -v scp >/dev/null 2>&1 || fail 'required command not found: scp'

if [[ -n "${ssh_port}" ]]; then
    [[ "${ssh_port}" =~ ^[1-9][0-9]*$ && "${ssh_port}" -le 65535 ]] ||
        fail "invalid SSH port: ${ssh_port}"
fi
ssh_args=(-o BatchMode=yes)
scp_args=(-q -o BatchMode=yes)
if [[ -n "${ssh_port}" ]]; then
    ssh_args+=(-p "${ssh_port}")
    scp_args+=(-P "${ssh_port}")
fi

if [[ -z "${shard_bin}" ]]; then
    if [[ -x "${REPO}/build/bin/potluck-shard" ]]; then
        shard_bin="${REPO}/build/bin/potluck-shard"
    elif command -v potluck-shard >/dev/null 2>&1; then
        shard_bin="$(command -v potluck-shard)"
    else
        fail 'cannot locate potluck-shard (set POTLUCK_SHARD_BIN)'
    fi
fi
[[ -x "${shard_bin}" ]] || fail "potluck-shard is not executable: ${shard_bin}"

# Parse and validate the route emitted by the server. The route is ordered and
# covers every model layer exactly once, so its end points are sharder bounds.
declare -a route_owner route_start route_end route_index
bounds_csv="0"
line_count=0
last_end=0
while read -r index window_owner start end extra; do
    [[ -n "${index:-}" ]] || continue
    [[ "${index}" == \#* ]] && continue
    [[ -n "${window_owner:-}" && -n "${start:-}" && -n "${end:-}" ]] ||
        fail "invalid route line: ${index:-}"
    [[ -z "${extra:-}" ]] || fail "route line has too many fields"
    [[ "${index}" =~ ^[0-9]+$ && "${window_owner}" =~ ^[0-9]+$ &&
       "${start}" =~ ^[0-9]+$ && "${end}" =~ ^[0-9]+$ ]] ||
        fail "invalid route line: ${index} ${window_owner} ${start} ${end}"
    [[ "${index}" -eq "${line_count}" ]] ||
        fail "route window indexes must start at zero and be ordered"
    [[ "${start}" -eq "${last_end}" && "${start}" -lt "${end}" ]] ||
        fail "route windows must be contiguous and non-empty"
    route_index[${line_count}]="${index}"
    route_owner[${line_count}]="${window_owner}"
    route_start[${line_count}]="${start}"
    route_end[${line_count}]="${end}"
    bounds_csv+=",${end}"
    last_end="${end}"
    line_count=$((line_count + 1))
done < "${route_file}"
[[ "${line_count}" -gt 0 && "${last_end}" -gt 0 ]] ||
    fail 'route file has no windows'

model_base="$(basename "${model}")"
model_stem="${model_base%.*}"
model_digest="$(sha256_file "${model}")"
route_digest="$(sha256_file "${route_file}")"
cache_dir="${cache_root}/${model_digest}-${route_digest}"
mkdir -p "${cache_root}"
if [[ ! -f "${cache_dir}/.complete" ]]; then
    rm -rf "${cache_dir}"
    mkdir -p "${cache_dir}"
    printf 'potluck-deploy: creating %u route shards\n' "${line_count}" >&2
    "${shard_bin}" "${model}" --bounds "${bounds_csv}" --outdir "${cache_dir}"
    touch "${cache_dir}/.complete"
fi

# Determine the target platform before selecting a payload. A payload directory
# is never copied across platforms: its libzmq ABI and loader paths are local.
remote_platform="$(ssh "${ssh_args[@]}" "${target}" 'uname -sm 2>/dev/null')" ||
    fail "cannot inspect platform on ${target}"
case "${remote_platform}" in
    'Darwin arm64'*) payload_name='mac-arm64' ;;
    'Linux x86_64'*) payload_name='linux-x86_64' ;;
    'Linux amd64'*) payload_name='linux-x86_64' ;;
    'Linux aarch64'*) payload_name='linux-aarch64' ;;
    'Linux arm64'*) payload_name='linux-arm64' ;;
    *) fail "unsupported remote platform: ${remote_platform}" ;;
esac
payload_dir="${dist_dir}/${payload_name}"
[[ -d "${payload_dir}" ]] ||
    fail "missing ${payload_name} payload: ${payload_dir}"
[[ -f "${payload_dir}/potluck-build-id" ]] ||
    fail "payload has no potluck-build-id: ${payload_dir}"

# The staging scripts record every shipped file in potluck-build-id. Verify the
# local payload before sending it, then verify the same bytes on the target.
declare -a payload_files
payload_files=(potluck-node potluck-worker)
while read -r checksum name extra; do
    [[ -n "${checksum:-}" ]] || continue
    [[ "${checksum}" == commit ]] && continue
    [[ -z "${extra:-}" && "${checksum}" =~ ^[[:xdigit:]]{64}$ ]] ||
        fail "invalid payload checksum record"
    [[ "${name}" != */* && -f "${payload_dir}/${name}" ]] ||
        fail "payload checksum names a missing file: ${name}"
    actual="$(sha256_file "${payload_dir}/${name}")"
    [[ "${actual}" == "${checksum}" ]] ||
        fail "payload checksum mismatch: ${name}"
    found=0
    for known in "${payload_files[@]}"; do
        [[ "${known}" == "${name}" ]] && found=1
    done
    [[ "${found}" == 1 ]] || payload_files+=("${name}")
done < "${payload_dir}/potluck-build-id"

owned_count=0
declare -a owned_indexes owned_files
for ((i = 0; i < line_count; ++i)); do
    [[ "${route_owner[i]}" -eq "${owner}" ]] || continue
    shard_name="${model_stem}.potluck-${route_index[i]}of${line_count}.gguf"
    shard_path="${cache_dir}/${shard_name}"
    [[ -s "${shard_path}" ]] || fail "missing generated shard: ${shard_path}"
    owned_indexes[${owned_count}]="${route_index[i]}"
    owned_files[${owned_count}]="${shard_name}"
    owned_count=$((owned_count + 1))
done
[[ "${owned_count}" -gt 0 ]] || fail "owner ${owner} has no route windows"

local_stage="$(mktemp -d "${TMPDIR:-/tmp}/potluck-deploy.XXXXXX")"
cleanup() {
    if [[ -n "${local_stage}" && -d "${local_stage}" ]]; then
        rm -rf "${local_stage}"
    fi
}
trap cleanup EXIT

for name in "${payload_files[@]}"; do
    cp -f "${payload_dir}/${name}" "${local_stage}/${name}"
done
cp -f "${payload_dir}/potluck-build-id" "${local_stage}/potluck-build-id"
for name in "${owned_files[@]}"; do
    cp -f "${cache_dir}/${name}" "${local_stage}/${name}"
done

manifest="${local_stage}/potluck-shards.manifest"
{
    printf 'version 1\n'
    printf 'model %s\n' "${model_base}"
    printf 'model_sha256 %s\n' "${model_digest}"
    printf 'owner %s\n' "${owner}"
    printf 'window_count %u\n' "${owned_count}"
    for ((i = 0; i < line_count; ++i)); do
        [[ "${route_owner[i]}" -eq "${owner}" ]] || continue
        shard_name="${model_stem}.potluck-${route_index[i]}of${line_count}.gguf"
        shard_digest="$(sha256_file "${cache_dir}/${shard_name}")"
        printf 'window %s %s %s %s %s %s\n' \
            "${route_index[i]}" "${owner}" "${route_start[i]}" \
            "${route_end[i]}" "${shard_name}" "${shard_digest}"
    done
} > "${manifest}"

checksums="${local_stage}/potluck-deploy.sha256"
: > "${checksums}"
for path in "${local_stage}"/*; do
    name="$(basename "${path}")"
    [[ "${name}" == 'potluck-deploy.sha256' ]] && continue
    printf '%s  %s\n' "$(sha256_file "${path}")" "${name}" >> "${checksums}"
done
remote_home="$(ssh "${ssh_args[@]}" "${target}" 'printf %s "$HOME"')" ||
    fail "cannot inspect home directory on ${target}"
[[ "${remote_home}" == /* && "${remote_home}" != *[[:space:]]* ]] ||
    fail "invalid remote home directory: ${remote_home}"
remote_prefix="${remote_home}/potluck"
remote_tmp="${remote_prefix}/.incoming-${route_digest}-${owner}-$$"
remote_tmp_q="$(shell_quote "${remote_tmp}")"
remote_prefix_q="$(shell_quote "${remote_prefix}")"
ssh_cmd() {
    ssh "${ssh_args[@]}" "${target}" "$1"
}
ssh_cmd "set -eu; mkdir -p ${remote_tmp_q}; rm -rf ${remote_tmp_q}/*"
scp "${scp_args[@]}" "${local_stage}"/* "${target}:${remote_tmp}/"

verify_cmd="set -eu; cd ${remote_tmp_q}; if command -v sha256sum >/dev/null 2>&1; then sha256sum -c potluck-deploy.sha256; elif command -v shasum >/dev/null 2>&1; then while read -r sum name; do test \"\${sum}\" = \"\$(shasum -a 256 \"\${name}\" | cut -d' ' -f1)\"; done < potluck-deploy.sha256; else exit 1; fi"
if ! ssh_cmd "${verify_cmd}"; then
    ssh_cmd "rm -rf ${remote_tmp_q}" || true
    fail "checksum verification failed on ${target}"
fi

# Replace only files managed by this deployment. Old generated shards are
# removed before the new manifest is made visible, so stale windows cannot be
# accidentally loaded after a topology change.
move_cmd="set -eu; mkdir -p ${remote_prefix_q}; find ${remote_prefix_q} -maxdepth 1 -type f -name '*.potluck-*.gguf' -delete;"
for path in "${local_stage}"/*; do
    name="$(basename "${path}")"
    move_cmd+=" mv ${remote_tmp_q}/$(shell_quote "${name}") ${remote_prefix_q}/$(shell_quote "${name}");"
done
move_cmd+=" chmod +x ${remote_prefix_q}/potluck-node ${remote_prefix_q}/potluck-worker; rm -rf ${remote_tmp_q}"
ssh_cmd "${move_cmd}"

printf 'potluck-deploy: %s owner=%s platform=%s windows=%s prefix=~/potluck\n' \
    "${target}" "${owner}" "${payload_name}" "${owned_count}"
